### PR TITLE
Update dashboard UI for issues #9, #7

### LINKED ISSUE #9: Dashboard UI improvements
Edited notes from a recent conversation with @kfogel:

- Use purple for "complete" features on the burndown chart like we do on the pie chart
  - Possibly make the legend refer to both charts to clarify the relationship between them
- Remove black borders from charts
- Show feature IDs in large modal that appears onclick of a bar in the burndown chart (ideally in title next to bold "Feature" heading)

### PR DESCRIPTION
**Pull request by pjsier**
Closes #9

* General updates to style
* Consolidates HTML in index.html (tried running `git mv` so that the diff is cleaner, but looks like that didn't work)
* Moves legend into top section to make it more clearly apply to both charts
* Removes black border around charts
* Adds feature IDs to the modal display
* Sets framework for #7 by adding [pym.js](http://blog.apps.npr.org/pym.js/) for embedding responsive iframes so that once GitHub Pages is enabled for this repo we can pull it directly into the projectpsm.org site without committing in the `gh-pages` branch
* Redraws charts on resizing to make them responsive (important for embed)

ui-updates

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Before I give you a full review, can I just say that gif is *so* useful?!  How did you make it?

**Comment by pjsier** [comment]
I used recordit.co, it's really nice for making quick gifs so I've started using it for PRs on some other projects. It keeps the file sizes relatively small compared to some other apps I've tried like Giphy

**Review by cecilia-donnelly — APPROVED** [review]
Looks great!  Thanks for moving forward on this @pjsier.  I'll merge.

@kfogel, you might want to take a look at this if you get a chance.

**Comment by cecilia-donnelly** [comment]
That's cool about recordit, @pjsier.  They don't have https on their site, though!  Come on, people!  (Of course, they also don't have a Linux version, boo.)

**Pull request merged**
